spring:
  datasource:
    password: MYSQL!usft3kaws
    url: jdbc:mysql://localhost:3306/server-pilot-db
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true